server:
    port: 1200

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/bills
        username: root
        password: 123456
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true